baseurl = "http://keanenguyen.com/"
theme = "cocoa-eh"
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Keane Nguyen"
title = "Keane Nguyen"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Keane Nguyen's personal website"
copyright = "Copyright 2017 Keane Nguyen" 
logofile = "img/logo.jpg"
faviconfile = "img/icon.jpg"
highlightjs = true
progressively = true
latestpostcount = 5
lang = "en"
github = "keanemind"
email = "keanekyn@gmail.com"
social_banner = "img/banner.png"
